version: "3.9"

services:

  api-gateway:
    build: ../services/api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - intelligence-engine
      - event-engine

  intelligence-engine:
    build: ../services/intelligence-engine
    ports:
      - "8001:8000"

  event-engine:
    build: ../services/event-engine
    ports:
      - "8002:8000"

  monitoring:
    build: ../services/monitoring
    ports:
      - "8003:8000"
